# Platform detection module for airplay2lib

set(AP2_WINDOWS FALSE)
set(AP2_MACOS FALSE)
set(AP2_IOS FALSE)
set(AP2_ANDROID FALSE)
set(AP2_LINUX FALSE)
set(AP2_POSIX FALSE)

if(CMAKE_SYSTEM_NAME STREQUAL "Windows")
    set(AP2_WINDOWS TRUE)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Darwin")
    if(CMAKE_OSX_SYSROOT MATCHES ".*iphoneos.*" OR CMAKE_OSX_SYSROOT MATCHES ".*iphonesimulator.*")
        set(AP2_IOS TRUE)
    else()
        set(AP2_MACOS TRUE)
    endif()
    set(AP2_POSIX TRUE)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Android")
    set(AP2_ANDROID TRUE)
    set(AP2_POSIX TRUE)
elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    set(AP2_LINUX TRUE)
    set(AP2_POSIX TRUE)
elseif(UNIX)
    set(AP2_LINUX TRUE)
    set(AP2_POSIX TRUE)
endif()

message(STATUS "[airplay2] Platform detection:")
message(STATUS "  Windows: ${AP2_WINDOWS}")
message(STATUS "  macOS:   ${AP2_MACOS}")
message(STATUS "  iOS:     ${AP2_IOS}")
message(STATUS "  Android: ${AP2_ANDROID}")
message(STATUS "  Linux:   ${AP2_LINUX}")
message(STATUS "  POSIX:   ${AP2_POSIX}")

# 字节序检测
# 交叉编译时 test_big_endian 会 try_run（编译+执行），target 二进制无法在 host 运行。
# 此时改用架构推断：aarch64 / arm64 / ppc64 等默认大端之外都是小端。
include(TestBigEndian)
if(CMAKE_CROSSCOMPILING)
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "ppc64|s390x")
        set(AP2_BIG_ENDIAN TRUE)
    else()
        set(AP2_BIG_ENDIAN FALSE)
    endif()
    message(STATUS "[airplay2] Cross-compiling: assuming big-endian=${AP2_BIG_ENDIAN} for ${CMAKE_SYSTEM_PROCESSOR}")
else()
    test_big_endian(AP2_BIG_ENDIAN)
endif()
if(AP2_BIG_ENDIAN)
    add_compile_definitions(AP2_BYTE_ORDER_BIG_ENDIAN=1)
else()
    add_compile_definitions(AP2_BYTE_ORDER_LITTLE_ENDIAN=1)
endif()
